### ISSUE TITLE
EE can't find administrator password on login page when first time starting

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-gitlab#11]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
```
    "end_check_versions.stdout_lines": [
        "Docker version 20.10.7, build f0df350",
        "gitlab-ee 13.12.3",
        "System version: CentOS 7.9",
        "Image name: gitlabxuwei-CentOS7.9"
    ]
```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/121474416-a4442800-c9f6-11eb-978f-ea72bfec5a83.png)

**Comment by qiaofeng1227** [comment]
image error, please make a new gitlab ee on aliyun
