### ISSUE TITLE
upgrade from v13.2.1 to v13.8.2

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-gitlab#3]
13.2.1(13.3.5) to 13.6.3

**Comment by zxc916684603** [comment]
aws    

amazonlinux2
--
error :  TASK [gitlab : System Update]
when I execuate `yum update`:
result:
```shell
Error: Package: python2-rpm-4.11.3-40.amzn2.0.5.x86_64 (amzn2-core)
           Requires: rpm = 4.11.3-40.amzn2.0.5
           Removing: rpm-4.11.3-40.amzn2.0.4.x86_64 (installed)
               rpm = 4.11.3-40.amzn2.0.4
           Updated By: rpm-4.11.3-45.el7.x86_64 (base)
               rpm = 4.11.3-45.el7
           Available: rpm-4.11.3-25.amzn2.0.1.x86_64 (amzn2-core)
               rpm = 4.11.3-25.amzn2.0.1
           Available: rpm-4.11.3-25.amzn2.0.3.x86_64 (amzn2-core)
               rpm = 4.11.3-25.amzn2.0.3
           Available: rpm-4.11.3-40.amzn2.0.3.x86_64 (amzn2-core)
               rpm = 4.11.3-40.amzn2.0.3
           Available: rpm-4.11.3-40.amzn2.0.5.x86_64 (amzn2-core)
               rpm = 4.11.3-40.amzn2.0.5
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by jiaosir-cn** [comment]
test

**Comment by jiaosir-cn** [comment]
Platform: AWS
Environment: Ubuntu20.04
ip: 3.90.83.248
Installation error
![gitlab](https://user-images.githubusercontent.com/76861519/107174545-74175900-6a05-11eb-952d-e12798838db9.png)

**Comment by jiaosir-cn** [comment]
Platform: Alibaba Cloud
Environment: Ubuntu20.04
ip: 47.243.19.150
Installation error
![gitlab](https://user-images.githubusercontent.com/76861519/107174631-ade85f80-6a05-11eb-9e56-4e1676885170.png)

**Comment by jiaosir-cn** [comment]
Platform: AWS
Environment: Linux2
ip: 54.167.173.196
The installation went well, the web interface cannot be accessed, 502 error
![gitlab](https://user-images.githubusercontent.com/76861519/107179982-c448e800-6a12-11eb-870d-915b7c0d2be1.png)

**Comment by jiaosir-cn** [comment]
Platform: Alibaba Cloud
Environment: CentOS7.9
ip: 47.242.248.117
The installation went well, the web interface cannot be accessed, 502 error
![gitlab](https://user-images.githubusercontent.com/76861519/107180479-bf386880-6a13-11eb-9911-24997e57c0b1.png)

**Comment by chendelin1982** [comment]
done
